// Test vectors generated by server/crypto_vectors_test.go
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Helper hex conversions
function fromHex(hex) {
  const bytes = new Uint8Array(hex.length / 2);
  for (let i = 0; i < hex.length; i += 2) {
    bytes[i / 2] = parseInt(hex.substring(i, i + 2), 16);
  }
  return bytes;
}

function toHex(bytes) {
  return Array.from(new Uint8Array(bytes))
    .map(b => b.toString(16).padStart(2, '0'))
    .join('');
}

function pad256(data) {
  let target = 256;
  while (target <= data.length) target += 256;
  const padded = new Uint8Array(target);
  padded.set(data);
  padded[data.length] = 0x80;
  return padded;
}

function unpad256(data) {
  const arr = new Uint8Array(data);
  for (let i = arr.length - 1; i >= 0; i--) {
    if (arr[i] === 0x80) return arr.slice(0, i);
    if (arr[i] !== 0x00) break;
  }
  throw new Error('invalid padding');
}

export async function runCryptoVectorTests() {
  console.log('=== Running Yori Crypto Vector Verification (JS vs Go) ===');
  
  const vectorsPath = path.resolve(__dirname, '../../vectors.json');
  const vectors = JSON.parse(fs.readFileSync(vectorsPath, 'utf8'));

  // 1. X25519 ECDH Key Agreement
  const x25519Prefix = fromHex('302e020100300506032b656e04220420');
  const alicePrivPkcs8 = new Uint8Array(x25519Prefix.length + 32);
  alicePrivPkcs8.set(x25519Prefix);
  alicePrivPkcs8.set(fromHex(vectors.alice_x25519_priv_hex), x25519Prefix.length);

  const alicePrivKey = await crypto.subtle.importKey('pkcs8', alicePrivPkcs8, { name: 'X25519' }, true, ['deriveBits', 'deriveKey']);
  const bobPubKey = await crypto.subtle.importKey('raw', fromHex(vectors.bob_x25519_pub_hex), { name: 'X25519' }, true, []);

  const sharedBits = await crypto.subtle.deriveBits({ name: 'X25519', public: bobPubKey }, alicePrivKey, 256);
  const sharedHex = toHex(sharedBits);

  if (sharedHex !== vectors.shared_secret_hex) {
    throw new Error(`X25519 shared secret mismatch:\nExpected: ${vectors.shared_secret_hex}\nGot:      ${sharedHex}`);
  }
  console.log('  [PASS] X25519 shared secret matches Go byte-for-byte');

  // 2. HKDF-SHA256 Directional & PreSession Keys
  const hkdfKey = await crypto.subtle.importKey('raw', sharedBits, 'HKDF', false, ['deriveBits', 'deriveKey']);
  const salt = fromHex(vectors.salt_hex);

  const sendKeyBits = await crypto.subtle.deriveBits({
    name: 'HKDF',
    hash: 'SHA-256',
    salt: salt,
    info: new TextEncoder().encode('yori-send-v1')
  }, hkdfKey, 256);
  if (toHex(sendKeyBits) !== vectors.send_key_hex) {
    throw new Error('HKDF send_key mismatch');
  }
  console.log('  [PASS] HKDF send key ("yori-send-v1") matches Go');

  const recvKeyBits = await crypto.subtle.deriveBits({
    name: 'HKDF',
    hash: 'SHA-256',
    salt: salt,
    info: new TextEncoder().encode('yori-recv-v1')
  }, hkdfKey, 256);
  if (toHex(recvKeyBits) !== vectors.receive_key_hex) {
    throw new Error('HKDF receive_key mismatch');
  }
  console.log('  [PASS] HKDF receive key ("yori-recv-v1") matches Go');

  const preKeyBits = await crypto.subtle.deriveBits({
    name: 'HKDF',
    hash: 'SHA-256',
    salt: salt,
    info: new TextEncoder().encode('yori-presession-v1')
  }, hkdfKey, 256);
  if (toHex(preKeyBits) !== vectors.presession_key_hex) {
    throw new Error('HKDF presession_key mismatch');
  }
  console.log('  [PASS] HKDF pre-session key ("yori-presession-v1") matches Go');

  // 3. AES-256-GCM Encryption, Padding & Decryption
  const aesKey = await crypto.subtle.importKey('raw', sendKeyBits, { name: 'AES-GCM' }, false, ['encrypt', 'decrypt']);
  const nonce = fromHex(vectors.aes_nonce_hex);
  const aad = new TextEncoder().encode(vectors.aad_message);
  const rawPlaintext = new TextEncoder().encode(vectors.plaintext);
  const padded = pad256(rawPlaintext);

  if (toHex(padded) !== vectors.padded_plaintext_hex) {
    throw new Error('pad256 output mismatch');
  }
  console.log('  [PASS] 256-byte padding matches Go');

  const ciphertextBuf = await crypto.subtle.encrypt({ name: 'AES-GCM', iv: nonce, additionalData: aad }, aesKey, padded);
  const ciphertextHex = toHex(ciphertextBuf);

  if (ciphertextHex !== vectors.ciphertext_hex) {
    throw new Error(`AES-256-GCM ciphertext mismatch:\nExpected: ${vectors.ciphertext_hex}\nGot:      ${ciphertextHex}`);
  }
  console.log('  [PASS] AES-256-GCM ciphertext with AAD matches Go byte-for-byte');

  // Decrypt Go's ciphertext
  const decryptedBuf = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: nonce, additionalData: aad }, aesKey, fromHex(vectors.ciphertext_hex));
  const unpaddedBytes = unpad256(decryptedBuf);
  const recoveredText = new TextDecoder().decode(unpaddedBytes);
  if (recoveredText !== vectors.plaintext) {
    throw new Error('Decryption recovery mismatch');
  }
  console.log('  [PASS] AES-256-GCM decryption of Go payload verified');

  // 4. Ed25519 Identity Signature, Verification & Fingerprint
  const edPrefix = fromHex('302e020100300506032b657004220420');
  const edSeed = fromHex(vectors.ed25519_seed_hex);
  const edPkcs8 = new Uint8Array(edPrefix.length + 32);
  edPkcs8.set(edPrefix);
  edPkcs8.set(edSeed, edPrefix.length);

  const edPrivKey = await crypto.subtle.importKey('pkcs8', edPkcs8, { name: 'Ed25519' }, true, ['sign']);
  const edPubKeyBytes = fromHex(vectors.ed25519_pub_hex);
  const edPubKey = await crypto.subtle.importKey('raw', edPubKeyBytes, { name: 'Ed25519' }, true, ['verify']);

  const signedMsg = new TextEncoder().encode(vectors.ed25519_msg);
  const sigBuf = await crypto.subtle.sign({ name: 'Ed25519' }, edPrivKey, signedMsg);
  const sigHex = toHex(sigBuf);

  if (sigHex !== vectors.ed25519_sig_hex) {
    throw new Error('Ed25519 signature mismatch');
  }
  console.log('  [PASS] Ed25519 signature matches Go byte-for-byte');

  const valid = await crypto.subtle.verify({ name: 'Ed25519' }, edPubKey, fromHex(vectors.ed25519_sig_hex), signedMsg);
  if (!valid) {
    throw new Error('Ed25519 verification failed');
  }
  console.log('  [PASS] Ed25519 signature verified');

  const fpHex = toHex(await crypto.subtle.digest('SHA-256', edPubKeyBytes));
  if (fpHex !== vectors.fingerprint_hex) {
    throw new Error('Fingerprint SHA-256 mismatch');
  }
  console.log('  [PASS] Identity fingerprint SHA-256 matches Go');

  console.log('=== ALL CRYPTO VECTOR TESTS PASSED (100% COMPATIBLE) ===');
}

runCryptoVectorTests().catch(err => {
  console.error('[FAIL]', err);
  process.exit(1);
});
